"""Write a GeneratedEval to disk as YAML plus a companion pytest module.

The YAML is the source of truth — human-editable, diffable, and what
`regress run evals/` reads directly. The pytest module is a thin generated
shim so `pytest evals/` also works with no Regress server involved, per
CLAUDE.md's "everything is also a file" principle: the eval must never
hold the user's test suite hostage.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from regress.evalgen.generate import GeneratedEval

_PYTEST_MODULE_TEMPLATE = '''"""Generated by `regress evalgen` — do not hand-edit.

Edit the paired {yaml_name} instead and regenerate, or edit both if you're
adding a case Regress didn't have a trace for yet.
"""

from pathlib import Path

import pytest

from regress.evalgen.load import load_eval_file
from regress.evalgen.run import EvalOutcome, run_eval_case

_EVAL = load_eval_file(Path(__file__).with_name({yaml_name!r}))


@pytest.mark.parametrize(
    "case", _EVAL.cases, ids=[c.trace_id for c in _EVAL.cases]
)
def test_{test_name}(case: object) -> None:
    outcome: EvalOutcome = run_eval_case(_EVAL, case)  # type: ignore[arg-type]
    assert outcome.passed, outcome.reasoning
'''


def eval_to_dict(eval_: GeneratedEval) -> dict[str, object]:
    assertion: dict[str, object] = {"type": eval_.assertion.type}
    if eval_.assertion.check is not None:
        assertion["check"] = eval_.assertion.check
    if eval_.assertion.params:
        assertion["params"] = eval_.assertion.params
    if eval_.assertion.rubric is not None:
        assertion["rubric"] = eval_.assertion.rubric

    return {
        "issue_id": eval_.issue_id,
        "issue_title": eval_.issue_title,
        "name": eval_.name,
        "assertion": assertion,
        "cases": [
            {"trace_id": c.trace_id, "input": c.input, "bad_output": c.bad_output}
            for c in eval_.cases
        ],
    }


def write_eval(eval_: GeneratedEval, directory: Path) -> tuple[Path, Path]:
    """Write `<name>.yaml` and `test_<name>.py` into `directory`.

    Returns (yaml_path, pytest_path). Overwrites any existing files with
    the same name — regenerating an eval for an issue replaces it rather
    than accumulating duplicates.
    """
    directory.mkdir(parents=True, exist_ok=True)
    yaml_path = directory / f"{eval_.name}.yaml"
    pytest_path = directory / f"test_{eval_.name.replace('-', '_')}.py"

    yaml_path.write_text(yaml.safe_dump(eval_to_dict(eval_), sort_keys=False))
    pytest_path.write_text(
        _PYTEST_MODULE_TEMPLATE.format(
            yaml_name=yaml_path.name,
            test_name=eval_.name.replace("-", "_"),
        )
    )
    return yaml_path, pytest_path
